const dirs = {
    buff: document.querySelector(".buff"),
    imgSword: document.querySelector(".img"),
    warrior: document.querySelector(".warriorDude"),
    warriorContainer: document.querySelector(".warrior"),
    warriroHealt: document.querySelector(".health-warrior-item"),
    GloryHealth: document.querySelector(".health_item"),
    invAdd:document.querySelectorAll(".block"),
    container:document.querySelector(".container"),
    loseIcon: document.querySelector(".lose"),
    spawnWarrior: document.querySelector(".spawn-warrior"),
    buffContainer: document.querySelector(".buff-container"),
    inventory:document.querySelector(".inventory"),
    id:0,
    counterWarrior:0,
    counterInventroy:0,
    randomPosition:22,
    scoreI:document.querySelector(".ScoreItem"),
    score:0,
    counterBuff:0
}