import "./AttackAnimation.js"
import "./LocalStorage.js"
import "./DamageBoss.js"
import "./SubscribeKillDamageWarrior.js"
import "./subscribeDamageKillGlory.js"
import "./damageGlory.js"
import "./SpawnRandomBuff.js"
import "./ClearSomeElLocalStorage.js"
import { playAudio } from "../FirstPageJs/playAudio.js"
import { soundDragon } from "../FirstPageJs/audioM.js"
playAudio(soundDragon)
